version: "3.0"
services:
  test:
    image: beamcorp/bql-dev
    container_name: bql-test
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    command: npm test
# currently unused, waiting for test suites